services:
  - type: web
    name: collabstudy-frontend
    env: node
    buildCommand: |
      cd collabstudy-react
      npm install
      npm run build
    startCommand: |
      cd collabstudy-react
      serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://collabstudy-backend.onrender.com
    autoDeploy: true 