services:
  - type: web
    name: collabstudy-frontend
    env: node
    buildCommand: |
      npm install
      npm install -g serve
      npm run build
    startCommand: serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://collabstudy-backend.onrender.com
    autoDeploy: true 