services:
  - type: web
    name: collabstudy-frontend
    env: node
    nodeVersion: 18.19.1
    buildCommand: |
      yarn install
      yarn build
    startCommand: serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://collabstudy-backend.onrender.com
    autoDeploy: true 