services:
  - type: web
    name: collabstudy-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /api/auth/test
    autoDeploy: true

  - type: web
    name: collabstudy-frontend
    env: node
    buildCommand: |
      cd collabstudy-react
      npm install
      npm run build
    startCommand: |
      cd collabstudy-react
      serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://collabstudy-backend.onrender.com
    autoDeploy: true 